/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frontend.pages;

import Backend.DB_FETCHER;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        this.setResizable(false);            // cannot resize
        this.setClosable(false);             // cannot close
        this.setIconifiable(false);          // cannot minimize
        this.setMaximizable(false); 
        setDashboardCounters();
        setBarGraphValueForCounters();
    }
    
    private void setDashboardCounters(){
        totalResidentsVal.setText(String.valueOf(DB_FETCHER.fetchNumberOfResidents()));
        activeBlottersVal.setText(String.valueOf(DB_FETCHER.fetchNumberOfActiveBlotters()));
        certificateRecordVal.setText(String.valueOf(DB_FETCHER.fetchNumberOfCertsRecoreded()));
        OfficialCountVal.setText(String.valueOf(DB_FETCHER.fetchOfficialCount()));
    }
    
    private void setBarGraphValueForCounters(){
        barGraphForCounters.setBarValue("Total Residents",DB_FETCHER.fetchNumberOfResidents());
        barGraphForCounters.setBarValue("Active Blotters", DB_FETCHER.fetchNumberOfActiveBlotters());
        barGraphForCounters.setBarValue("Certificate Records", DB_FETCHER.fetchNumberOfCertsRecoreded());
        barGraphForCounters.setBarValue("Official Counts", DB_FETCHER.fetchOfficialCount());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        draggableShadowPanel2 = new Utilities.DraggableShadowPanel();
        jLabel2 = new javax.swing.JLabel();
        totalResidentsVal = new javax.swing.JLabel();
        panelRound2 = new Utilities.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        draggableShadowPanel3 = new Utilities.DraggableShadowPanel();
        jLabel6 = new javax.swing.JLabel();
        activeBlottersVal = new javax.swing.JLabel();
        panelRound6 = new Utilities.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        draggableShadowPanel15 = new Utilities.DraggableShadowPanel();
        jLabel8 = new javax.swing.JLabel();
        OfficialCountVal = new javax.swing.JLabel();
        panelRound8 = new Utilities.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        draggableShadowPanel17 = new Utilities.DraggableShadowPanel();
        jLabel4 = new javax.swing.JLabel();
        certificateRecordVal = new javax.swing.JLabel();
        panelRound4 = new Utilities.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        draggableShadowPanel1 = new Utilities.DraggableShadowPanel();
        barGraphForCounters = new Utilities.ModernBarGraph();

        setBackground(new java.awt.Color(221, 233, 235));
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(939, 624));

        jPanel1.setBackground(new java.awt.Color(221, 233, 235));

        draggableShadowPanel2.setShadowColor(new java.awt.Color(76, 159, 246));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Residents");

        totalResidentsVal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalResidentsVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalResidentsVal.setText("0");

        panelRound2.setBackground(new java.awt.Color(76, 159, 246));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout draggableShadowPanel2Layout = new javax.swing.GroupLayout(draggableShadowPanel2);
        draggableShadowPanel2.setLayout(draggableShadowPanel2Layout);
        draggableShadowPanel2Layout.setHorizontalGroup(
            draggableShadowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(draggableShadowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(draggableShadowPanel2Layout.createSequentialGroup()
                        .addComponent(totalResidentsVal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        draggableShadowPanel2Layout.setVerticalGroup(
            draggableShadowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(draggableShadowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(draggableShadowPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalResidentsVal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        draggableShadowPanel3.setShadowColor(new java.awt.Color(255, 189, 89));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Active Blotters");

        activeBlottersVal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        activeBlottersVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activeBlottersVal.setText("0");

        panelRound6.setBackground(new java.awt.Color(255, 145, 77));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout draggableShadowPanel3Layout = new javax.swing.GroupLayout(draggableShadowPanel3);
        draggableShadowPanel3.setLayout(draggableShadowPanel3Layout);
        draggableShadowPanel3Layout.setHorizontalGroup(
            draggableShadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(draggableShadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(draggableShadowPanel3Layout.createSequentialGroup()
                        .addComponent(activeBlottersVal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        draggableShadowPanel3Layout.setVerticalGroup(
            draggableShadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(draggableShadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(draggableShadowPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activeBlottersVal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        draggableShadowPanel15.setShadowColor(new java.awt.Color(219, 133, 133));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Official Count");

        OfficialCountVal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        OfficialCountVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OfficialCountVal.setText("0");

        panelRound8.setBackground(new java.awt.Color(255, 87, 87));
        panelRound8.setRoundBottomLeft(20);
        panelRound8.setRoundBottomRight(20);
        panelRound8.setRoundTopLeft(20);
        panelRound8.setRoundTopRight(20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout draggableShadowPanel15Layout = new javax.swing.GroupLayout(draggableShadowPanel15);
        draggableShadowPanel15.setLayout(draggableShadowPanel15Layout);
        draggableShadowPanel15Layout.setHorizontalGroup(
            draggableShadowPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(draggableShadowPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(draggableShadowPanel15Layout.createSequentialGroup()
                        .addComponent(OfficialCountVal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        draggableShadowPanel15Layout.setVerticalGroup(
            draggableShadowPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(draggableShadowPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(draggableShadowPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OfficialCountVal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        draggableShadowPanel17.setShadowColor(new java.awt.Color(126, 217, 87));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Certificate Record");

        certificateRecordVal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        certificateRecordVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certificateRecordVal.setText("0");

        panelRound4.setBackground(new java.awt.Color(126, 217, 87));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout draggableShadowPanel17Layout = new javax.swing.GroupLayout(draggableShadowPanel17);
        draggableShadowPanel17.setLayout(draggableShadowPanel17Layout);
        draggableShadowPanel17Layout.setHorizontalGroup(
            draggableShadowPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel17Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(draggableShadowPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(certificateRecordVal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        draggableShadowPanel17Layout.setVerticalGroup(
            draggableShadowPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(draggableShadowPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(draggableShadowPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(certificateRecordVal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        draggableShadowPanel1.setBackground(new java.awt.Color(255, 255, 255));

        barGraphForCounters.setBackground(new java.awt.Color(255, 255, 255));
        barGraphForCounters.setRequestFocusEnabled(false);

        javax.swing.GroupLayout barGraphForCountersLayout = new javax.swing.GroupLayout(barGraphForCounters);
        barGraphForCounters.setLayout(barGraphForCountersLayout);
        barGraphForCountersLayout.setHorizontalGroup(
            barGraphForCountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barGraphForCountersLayout.setVerticalGroup(
            barGraphForCountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout draggableShadowPanel1Layout = new javax.swing.GroupLayout(draggableShadowPanel1);
        draggableShadowPanel1.setLayout(draggableShadowPanel1Layout);
        draggableShadowPanel1Layout.setHorizontalGroup(
            draggableShadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barGraphForCounters, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );
        draggableShadowPanel1Layout.setVerticalGroup(
            draggableShadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draggableShadowPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barGraphForCounters, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(draggableShadowPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(draggableShadowPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(draggableShadowPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(draggableShadowPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(draggableShadowPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(draggableShadowPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(draggableShadowPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(draggableShadowPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(draggableShadowPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(draggableShadowPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OfficialCountVal;
    private javax.swing.JLabel activeBlottersVal;
    private Utilities.ModernBarGraph barGraphForCounters;
    private javax.swing.JLabel certificateRecordVal;
    private Utilities.DraggableShadowPanel draggableShadowPanel1;
    private Utilities.DraggableShadowPanel draggableShadowPanel15;
    private Utilities.DraggableShadowPanel draggableShadowPanel17;
    private Utilities.DraggableShadowPanel draggableShadowPanel2;
    private Utilities.DraggableShadowPanel draggableShadowPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private Utilities.PanelRound panelRound2;
    private Utilities.PanelRound panelRound4;
    private Utilities.PanelRound panelRound6;
    private Utilities.PanelRound panelRound8;
    private javax.swing.JLabel totalResidentsVal;
    // End of variables declaration//GEN-END:variables
}
