/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.forms;

import Backend.DB_FETCHER;
import Frontend.pages.Officials;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import raven.toast.Notifications;


/**
 *
 * @author User
 */
public class OfficialsRegForm extends javax.swing.JFrame {

    private final Officials officials;
    private int mouseX, mouseY;
    private int editOfficialId = -1;
    private final Map<String, Integer> residentIdMap = new HashMap<>();

    public OfficialsRegForm(Officials off) {
        this.officials = off;
        initComponents();
        initSearchBarForOfficials();
        initOfficialPositionSelection();
    }
    
    private void initSearchBarForOfficials(){
        ResultSet result = DB_FETCHER.fetchAllResidents();
        if (result == null) return;
        List<String> suggestions = new ArrayList<>();
        try {
            while (result.next()) {
                int    id  = result.getInt("resident_id");
                String fn  = result.getString("first_name");
                String mn  = result.getString("middle_name");
                String ln  = result.getString("last_name");
                String fullName = (fn + (mn != null && !mn.isEmpty() ? " " + mn : "") + " " + ln).trim();
                if (!fullName.isEmpty()) {
                    suggestions.add(fullName);
                    residentIdMap.put(fullName, id);
                }
            }
            officialNameDropdown.setItems(suggestions);
        } catch (SQLException ex) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Error loading residents.");
        }
    }

    private int getSelectedResidentId() {
        String selected = officialNameDropdown.getText().trim();
        return residentIdMap.getOrDefault(selected, -1);
    }

    public void populateForEdit(int officialId) {
        this.editOfficialId = officialId;
        java.sql.ResultSet rs = Backend.DB_FETCHER.fetchOfficialById(officialId);
        if (rs == null) return;
        try {
            if (rs.next()) {
                int    residentId   = rs.getInt("official_resedential_id");
                String position     = rs.getString("position");
                java.sql.Date tStart = rs.getDate("term_start");
                java.sql.Date tEnd   = rs.getDate("term_end");
                String profileImage = rs.getString("profile_image");

                java.sql.ResultSet resData = Backend.DB_FETCHER.getOfficialsResidentialInfo(residentId);
                if (resData != null && resData.next()) {
                    String fn = resData.getString("first_name");
                    String mn = resData.getString("middle_name");
                    String ln = resData.getString("last_name");
                    String fullName = (fn + (mn != null && !mn.isEmpty() ? " " + mn : "") + " " + ln).trim();
                    officialNameDropdown.setText(fullName);
                }

                posCB.setSelectedItem(position);
                if (tStart != null) termstartTF.setDate(tStart.toLocalDate());
                if (tEnd   != null) termendTF.setDate(tEnd.toLocalDate());
                if (profileImage != null && !profileImage.isEmpty()) uploadimagePL.loadFromStoredPath(profileImage);
            }
        } catch (SQLException ex) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Error loading official data.");
        }
    }
    
    private void initOfficialPositionSelection(){
        posCB.addItem("None");
        posCB.addItem("Barangay Captain");
        posCB.addItem("Kagawad");
        posCB.addItem("(SK) Chairperson");
        posCB.addItem("Barangay Secretary");
        posCB.addItem("Barangay Treasurer");
        posCB.addItem("Barangay Tanod");
        posCB.addItem("Lupon Tagapamayapa Members");
        posCB.addItem("Barangay Health Workers");
        posCB.addItem("Daycare Workers");
        posCB.addItem("Volunteers");
    }
    
    /**
     * Creates new form ResidentForm
     * @param off
     */
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        uploadimagePL = new Utilities.CircleImagePanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        posCB = new Utilities.ModernComboBox();
        saveBtn = new Utilities.ModernButton();
        termstartTF = new Utilities.DatePickerField();
        termendTF = new Utilities.DatePickerField();
        officialNameDropdown = new Utilities.ModernDropdownPalette();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" OFFICIALS INFORMATION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout uploadimagePLLayout = new javax.swing.GroupLayout(uploadimagePL);
        uploadimagePL.setLayout(uploadimagePLLayout);
        uploadimagePLLayout.setHorizontalGroup(
            uploadimagePLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        uploadimagePLLayout.setVerticalGroup(
            uploadimagePLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel8.setText("Term Start");

        jLabel9.setText("Term End");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Position");

        posCB.setPlaceholder("Ex. Brgy. Captain");

        javax.swing.GroupLayout posCBLayout = new javax.swing.GroupLayout(posCB);
        posCB.setLayout(posCBLayout);
        posCBLayout.setHorizontalGroup(
            posCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        posCBLayout.setVerticalGroup(
            posCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        saveBtn.setText("SAVE");
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout termstartTFLayout = new javax.swing.GroupLayout(termstartTF);
        termstartTF.setLayout(termstartTFLayout);
        termstartTFLayout.setHorizontalGroup(
            termstartTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        termstartTFLayout.setVerticalGroup(
            termstartTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout termendTFLayout = new javax.swing.GroupLayout(termendTF);
        termendTF.setLayout(termendTFLayout);
        termendTFLayout.setHorizontalGroup(
            termendTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        termendTFLayout.setVerticalGroup(
            termendTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uploadimagePL, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(officialNameDropdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(posCB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(termstartTF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(termendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uploadimagePL, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(posCB, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(officialNameDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(termstartTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(termendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int residentId = getSelectedResidentId();
        
        if (residentId == -1) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Officials must be a resident.");
            return;
        }

        String position     = posCB.getSelectedItem() != null ? posCB.getSelectedItem() : "";
        java.time.LocalDate termStartDate = termstartTF.getDate();
        java.time.LocalDate termEndDate   = termendTF.getDate();
        String profileImage = uploadimagePL.getStoredFilePath() != null ? uploadimagePL.getStoredFilePath() : "";
        
        if (position.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Please select a position.");
            return;
        }
        if (termStartDate == null) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Please select a term start date.");
            return;
        }
        if (termEndDate == null) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Please select a term end date.");
            return;
        }

        java.sql.Date sqlTermStart = java.sql.Date.valueOf(termStartDate);
        java.sql.Date sqlTermEnd   = java.sql.Date.valueOf(termEndDate);

        if (editOfficialId == -1) {
            officials.receivedDataFromTheForm(profileImage, residentId, position, sqlTermStart, sqlTermEnd, "closed");
        } else {
            int result = Backend.DB_INSERT.updateOfficial(editOfficialId, profileImage, residentId, position, sqlTermStart, sqlTermEnd);
            Notifications.Type type = (result == 0) ? Notifications.Type.INFO : Notifications.Type.SUCCESS;
            String msg  = (result == 0) ? "Something went wrong while updating" : "Official updated successfully";
            Notifications.getInstance().show(type, msg);
            officials.refreshTable();
        }
        this.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        officials.updateButtonState();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private Utilities.ModernDropdownPalette officialNameDropdown;
    private Utilities.ModernComboBox posCB;
    private Utilities.ModernButton saveBtn;
    private Utilities.DatePickerField termendTF;
    private Utilities.DatePickerField termstartTF;
    private Utilities.CircleImagePanel uploadimagePL;
    // End of variables declaration//GEN-END:variables
}
