/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.forms;

import Backend.DB_FETCHER;
import Frontend.pages.Residents;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
//import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ResidentRegForm extends javax.swing.JFrame {
    private final Residents res;    
    private int mouseX, mouseY;
    private String buttonState = "Registration";
    /**
     * Creates new form ResidentForm
     * @param res
     */
    public ResidentRegForm(Residents res) {
        initComponents();
        initGenderCB();
        initStatusCB();
        this.res = res;
    }
    
    private void initGenderCB(){
        genderCB.setItems(List.of("Male", "Female", "Other"));
    }
    
    private void initStatusCB(){
        statCM.setItems(List.of("ACTIVE","INACTIVE","MOVED_OUT","DECEASED","TEMPORARY","UNDER_REVIEW","BLACKLISTED"));
    }

    private int residentID=0;
    public void populateForEdit(int residentId) {
        this.residentID = residentId;
        buttonState = "Edit";
        try {
            ResultSet rs = DB_FETCHER.fetchResidentByID(residentId);
            if (rs == null || !rs.next()) return;

            nameTF.setText(rs.getString("first_name"));
            middleNameTF.setText(rs.getString("middle_name") != null ? rs.getString("middle_name") : "");
            lastNameTF.setText(rs.getString("last_name"));

            String sex = rs.getString("sex");
            if (sex != null) genderCB.setSelectedItem(
                    sex.substring(0, 1).toUpperCase() + sex.substring(1).toLowerCase());

            java.sql.Date bd = rs.getDate("birth_date");
            if (bd != null) BdateTF.setDate(bd.toLocalDate());

            civilStatTF.setText(rs.getString("civil_status")  != null ? rs.getString("civil_status")  : "");
            nationalityTF.setText(rs.getString("nationality") != null ? rs.getString("nationality")   : "");
            addressTF.setText(rs.getString("address")         != null ? rs.getString("address")        : "");
            purokTF.setText(rs.getString("purok")             != null ? rs.getString("purok")          : "");
            lsTF.setText(rs.getString("length_of_stay")       != null ? rs.getString("length_of_stay") : "");

            String status = rs.getString("status");
            if (status != null) statCM.setSelectedItem(status);

            String imgPath = rs.getString("profile_image");
            if (imgPath != null && !imgPath.isEmpty()) uploadimagePL.loadFromStoredPath(imgPath);

        } catch (SQLException ex) {
            System.out.println("ERROR populating form: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        uploadimagePL = new Utilities.CircleImagePanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameTF = new Utilities.RoundedInputField();
        middleNameTF = new Utilities.RoundedInputField();
        genderCB = new Utilities.ModernComboBox();
        lastNameTF = new Utilities.RoundedInputField();
        addressTF = new Utilities.RoundedInputField();
        purokTF = new Utilities.RoundedInputField();
        nationalityTF = new Utilities.RoundedInputField();
        civilStatTF = new Utilities.RoundedInputField();
        statCM = new Utilities.ModernComboBox();
        saveBtn = new Utilities.ModernButton();
        BdateTF = new Utilities.DatePickerField();
        lsTF = new Utilities.RoundedInputField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESIDENT INFORMATION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        uploadimagePL.setRingThickness(1);

        javax.swing.GroupLayout uploadimagePLLayout = new javax.swing.GroupLayout(uploadimagePL);
        uploadimagePL.setLayout(uploadimagePLLayout);
        uploadimagePLLayout.setHorizontalGroup(
            uploadimagePLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        uploadimagePLLayout.setVerticalGroup(
            uploadimagePLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Firstname:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Middlename");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lastname");

        jLabel5.setText("Sex");

        jLabel6.setText("Birthdate");

        jLabel8.setText("Civil Status");

        jLabel9.setText("Nationality");

        jLabel10.setText("Purok");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Address");

        jLabel12.setText("Length of Stay");

        jLabel13.setText("Status");

        nameTF.setHPad(9);
        nameTF.setPlaceholder("Your first name");

        middleNameTF.setHPad(9);
        middleNameTF.setPlaceholder("Your middlename");

        genderCB.setPlaceholder("Gender Type");

        javax.swing.GroupLayout genderCBLayout = new javax.swing.GroupLayout(genderCB);
        genderCB.setLayout(genderCBLayout);
        genderCBLayout.setHorizontalGroup(
            genderCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        genderCBLayout.setVerticalGroup(
            genderCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        lastNameTF.setHPad(9);
        lastNameTF.setPlaceholder("Your lastname");

        addressTF.setHPad(9);
        addressTF.setPlaceholder("Ex. Maitum, Catigbian, Bohol");

        purokTF.setHPad(9);
        purokTF.setPlaceholder("Ex. Purok 1");

        nationalityTF.setHPad(9);
        nationalityTF.setPlaceholder("Ex. Filipino");

        civilStatTF.setHPad(9);
        civilStatTF.setPlaceholder("Ex. Single");

        statCM.setPlaceholder("Ex. Active");

        javax.swing.GroupLayout statCMLayout = new javax.swing.GroupLayout(statCM);
        statCM.setLayout(statCMLayout);
        statCMLayout.setHorizontalGroup(
            statCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        statCMLayout.setVerticalGroup(
            statCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        saveBtn.setText("SAVE");
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BdateTFLayout = new javax.swing.GroupLayout(BdateTF);
        BdateTF.setLayout(BdateTFLayout);
        BdateTFLayout.setHorizontalGroup(
            BdateTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        BdateTFLayout.setVerticalGroup(
            BdateTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        lsTF.setPlaceholder("Ex. 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(purokTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lsTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(genderCB, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(civilStatTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(nationalityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(BdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addComponent(statCM, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(15, 15, 15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(middleNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uploadimagePL, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadimagePL, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(middleNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purokTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationalityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statCM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(civilStatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BdateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(lsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(5, 5, 5))))
        );

        lsTF.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String firstName    = nameTF.getText().trim();
        String middleName   = middleNameTF.getText().trim();
        String lastName     = lastNameTF.getText().trim();
        String sex          = genderCB.getSelectedItem() != null ? genderCB.getSelectedItem() : "";
        java.time.LocalDate dateVal = BdateTF.getDate();
        String birthDate    = dateVal != null
                              ? dateVal.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"))
                              : "";
        String civilStatus  = civilStatTF.getText().trim();
        String nationality  = nationalityTF.getText().trim();
        String address      = addressTF.getText().trim();
        String purok        = purokTF.getText().trim();
        String lengthOfStay = lsTF.getText().trim();
        String profileImage = uploadimagePL.getStoredFilePath() != null ? uploadimagePL.getStoredFilePath() : "";
        String status       = statCM.getSelectedItem() != null ? statCM.getSelectedItem() : "";

        if (firstName.isEmpty() || lastName.isEmpty() || sex.isEmpty()
                || birthDate.isEmpty() || civilStatus.isEmpty()
                || nationality.isEmpty() || address.isEmpty()
                || purok.isEmpty() || status.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please fill in all required fields and select a birthdate.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(buttonState.equals("Registration")) res.receivedDataFromTheForm(
                firstName, middleName, lastName, sex, birthDate, civilStatus, nationality, address, purok, lengthOfStay, profileImage, status, "closed"
        );
        else res.UpdateTableFromEdit(
                residentID, firstName, middleName, lastName, sex, birthDate, civilStatus, nationality, address, purok, lengthOfStay, profileImage, status, "closed"
        );
        
        this.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Utilities.DatePickerField BdateTF;
    private Utilities.RoundedInputField addressTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private Utilities.RoundedInputField civilStatTF;
    private Utilities.ModernComboBox genderCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private Utilities.RoundedInputField lastNameTF;
    private Utilities.RoundedInputField lsTF;
    private Utilities.RoundedInputField middleNameTF;
    private Utilities.RoundedInputField nameTF;
    private Utilities.RoundedInputField nationalityTF;
    private Utilities.RoundedInputField purokTF;
    private Utilities.ModernButton saveBtn;
    private Utilities.ModernComboBox statCM;
    private Utilities.CircleImagePanel uploadimagePL;
    // End of variables declaration//GEN-END:variables
}
