/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.DB_INSERT;
import Utilities.PasswordHasher;
import Utilities.PopUpNotif;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Image;
import javax.swing.ImageIcon;
import raven.toast.Notifications;

/**
 *
 * @author User
 */
public class SignUpFrame extends javax.swing.JFrame {

    public SignUpFrame() {
        initComponents();
        initFields();
        ImageIcon icon = new ImageIcon("src/assets/maitum_logo8.png");
        Image image = icon.getImage();
        this.setIconImage(image);
        this.setTitle("BMS");
        Notifications.getInstance().setJFrame(this);
    }

    private void initFields(){
        usnTF.putClientProperty("JComponent.roundRect", true);
        usnTF.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Username");
        usnTF.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("assets/usnmIcon.svg"));
        usnTF.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        
        pwdPF.putClientProperty("JComponent.roundRect", true);
        pwdPF.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Password");
        pwdPF.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("assets/pwdIcon.svg"));
        pwdPF.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);  
        pwdPF.putClientProperty(FlatClientProperties.STYLE, "showRevealButton:true");
        pwdPF.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON,true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelRound1 = new Utilities.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usnTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pwdPF = new javax.swing.JPasswordField();
        signupBtn = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        SignUpF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGEMENT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 260, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/maitum_logo6.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 130));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BARANGAY  ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Account Registration");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Username");

        usnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usnTFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usnTFKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Password");

        pwdPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdPFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdPFKeyTyped(evt);
            }
        });

        signupBtn.setBackground(new java.awt.Color(0, 204, 204));
        signupBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("SIGNUP");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label.setText("Already have an account?");

        SignUpF.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        SignUpF.setForeground(new java.awt.Color(0, 51, 255));
        SignUpF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUpF.setText("SignIn");
        SignUpF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpFMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRound1Layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SignUpF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usnTF)
                    .addComponent(pwdPF)
                    .addComponent(signupBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(pwdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpF)
                    .addComponent(label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 340, 330));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SYSTEM ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Gemini_Generated_Image_g7xh4ng7xh4ng7xh.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MANAGEMENT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpFMouseExited
        SignUpF.setText("SignIn");
    }//GEN-LAST:event_SignUpFMouseExited

    private void SignUpFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpFMouseEntered
        String text = "<HTML><u>SignIn</u><HTML>";
        SignUpF.setText(text);
    }//GEN-LAST:event_SignUpFMouseEntered

    private void SignUpFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpFMouseClicked
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUpFMouseClicked

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        //Notifications.getInstance().show(Notifications.Type.INFO, "Opening Next Page");
        final String hashedpwd = PasswordHasher.hashPassword(String.valueOf(pwdPF.getPassword()));
        final String usn = usnTF.getText();
        if(usnTF.getText().trim().isEmpty() || pwdPF.getPassword().length == 0){
            if (usnTF.getText().trim().isEmpty()) {
                PopUpNotif.showFieldError(usnTF, "Username is required");
            }
            
            if (pwdPF.getPassword().length == 0) {
                PopUpNotif.showFieldError(pwdPF, "Password is required");
            }
        }else{
            int isUpdated = DB_INSERT.insertUser(usn, hashedpwd);
            Notifications.getInstance().show(
                        Notifications.Type.INFO, 
                        (isUpdated!=0 ? "Recorded Successfully" : "Not Recorded")
                );
        }
    }//GEN-LAST:event_signupBtnActionPerformed

    private void pwdPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPFKeyTyped
        if(String.valueOf(pwdPF.getPassword()).length()>11) evt.consume();
    }//GEN-LAST:event_pwdPFKeyTyped

    private void pwdPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPFKeyPressed
        if(String.valueOf(pwdPF.getPassword()).length()>=0)
        pwdPF.putClientProperty("JComponent.outline","success");
    }//GEN-LAST:event_pwdPFKeyPressed

    private void usnTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usnTFKeyTyped
        if(usnTF.getText().length()>11) evt.consume();
    }//GEN-LAST:event_usnTFKeyTyped

    private void usnTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usnTFKeyPressed
        if(usnTF.getText().length()>=0)
        usnTF.putClientProperty("JComponent.outline","success");
    }//GEN-LAST:event_usnTFKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignUpF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private Utilities.PanelRound panelRound1;
    private javax.swing.JPasswordField pwdPF;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField usnTF;
    // End of variables declaration//GEN-END:variables
}
